# Generated by Django 6.1.1 on 2026-09-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_item_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vegeterian',
            new_name='vegetarian',
        ),
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('restaurant', 'name')},
        ),
    ]
