# Generated by Django 6.1.1 on 2026-09-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_rename_vegeterian_item_vegetarian_item_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
