# Generated by Django 6.1.1 on 2026-09-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
