
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('open_signup', views.open_signup, name='open_signup'),
    path('open_signin', views.open_signin, name='open_signin'),
    path('verify_otp', views.verify_otp, name='verify_otp'),
    path('resend_otp', views.resend_otp, name='resend_otp'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('verify_reset_otp', views.verify_reset_otp, name='verify_reset_otp'),
    path('reset_password', views.reset_password, name='reset_password'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('admin_home', views.admin_home, name='admin_home'),
    path('open_add_restaurant', views.open_add_restaurant, name='open_add_restaurant'),
    path('add_restaurant', views.add_restaurant, name='add_restaurant'),
    path('open_show_restaurants', views.open_show_restaurants, name='open_show_restaurants'),
    path('open_update_restaurant/<int:restaurant_id>/', views.open_update_restaurant, name='open_update_restaurant'),
    path('update_restaurant/<int:restaurant_id>/', views.update_restaurant, name='update_restaurant'),
    path('toggle-restaurant-status/<int:restaurant_id>/',views.toggle_restaurant_status,name='toggle_restaurant_status'),
    path('delete_restaurant/<int:restaurant_id>/', views.delete_restaurant, name='delete_restaurant'),
    path('open_update_menu/<int:restaurant_id>', views.open_update_menu, name='open_update_menu'), 
    path('update_menu/<int:restaurant_id>', views.update_menu, name='update_menu'),
    path('open_update_item/<int:restaurant_id>/<int:item_id>', views.open_update_item, name='open_update_item'),
    path('update_item/<int:restaurant_id>/<int:item_id>', views.update_item, name='update_item'),
    path('delete_item/<int:restaurant_id>/<int:item_id>', views.delete_item, name='delete_item'),
    path('view_menu/<int:restaurant_id>/<str:username>', views.view_menu, name='view_menu'),  
    path('add_to_favorites/<int:restaurant_id>/<str:username>', views.add_to_favorites,name='add_to_favorites'),
    path('favorites/<str:username>',views.show_favorites,name='show_favorites'),
    path('remove_from_favorites/<int:restaurant_id>/<str:username>',views.remove_from_favorites,name='remove_from_favorites'),
    path('add_to_cart/<int:item_id>/<str:username>', views.add_to_cart, name='add_to_cart'),
    path('show_cart/<str:username>', views.show_cart, name='show_cart'),
    path('logout/', views.logout, name='logout'),
    path('increase_quantity/<int:cart_item_id>/<str:username>',views.increase_quantity,name='increase_quantity'),
    path('decrease_quantity/<int:cart_item_id>/<str:username>',views.decrease_quantity, name='decrease_quantity'),
    path('remove_from_cart/<int:cart_item_id>/<str:username>',views.remove_from_cart,name='remove_from_cart'),
    path('customer_home/<str:username>', views.customer_home, name='customer_home'),
    path('edit_profile/<str:username>',views.edit_profile,name='edit_profile'),
    path('add_address/<str:username>',views.add_address,name='add_address'),
    path('edit_address/<str:username>/<int:address_id>',views.edit_address,name='edit_address'),
    path('delete_address/<str:username>/<int:address_id>',views.delete_address, name='delete_address'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('show_customers/',views.show_customers,name='show_customers'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('place-order/', views.place_order, name='place_order'),
    path('order-confirmation/<int:order_id>/',views.order_confirmation,name='order_confirmation'),
    path('my_orders/<str:username>',views.my_orders,name='my_orders'),
    path('order-tracking/<int:order_id>/', views.order_tracking,name='order_tracking'),
    path( 'admin_orders/', views.admin_orders,name='admin_orders'),
    path('admin_orders/<int:order_id>/update/',views.update_order_status,name='update_order_status'),
]
